default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: soc_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: soc_test

production:
  <<: *default
  database: soc_production
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  username: soc
