default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: summon_player

development:
  <<: *default
  database: summon_player_development
  password: postgres

test:
  <<: *default
  database: summon_player_test

production:
  <<: *default
  database: summon_player_production
  password: <%= ENV["SUMMON_PLAYER_DATABASE_PASSWORD"] %>
