service: soc

image: tsvallender/soc

load_balancer:
  host: kernighan
  arch: arm64

servers:
  web:
    hosts:
      - www.tsvallender.co.uk
    options:
      network: kamal

volumes:
  - /srv/soc/storage:/rails/storage

registry:
  username: tsvallender
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    APPLICATION_HOST: tsvallender.co.uk
    DB_HOST: soc-postgres
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

builder:
  args:
    APPLICATION_HOST: tsvallender.co.uk
    RUBY_VERSION: 3.3.4
  arch: arm64
  remote: ssh://kamal@tsvallender.co.uk

accessories:
  postgres:
    image: postgres:16
    host: www.tsvallender.co.uk
    env:
      clear:
        POSTGRES_USER: soc
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - /srv/soc/data:/var/lib/postgresql/data
    options:
      network: kamal
